<?php

/**
 * Implementation of hook_menu()
 */
function tbx_rdf_menu() {
  $items['rdf/impact-areas.rdf'] = array(
    'page callback' => '_tbx_rdf_impact_areas_rdf',
    'page arguments' => array('impact-areas.rdf'),
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
  );
  return $items;
}

function hallo() {
  return "<h1>HALLO</h1>";
}
 
/**
 * Page callback for forcing a file to download
 */
function _tbx_rdf_impact_areas_rdf($filename) {

      $uri = 'public://';

      $wrapper = file_stream_wrapper_get_instance_by_uri('public://');
      $realpath = $wrapper->realpath();

      $filepath = $realpath. '/' . $filename;



      if (file_exists($filepath)) {

       #file_transfer($realpath, array('Content-disposition' => 'attachment;  filename='.$filename));


        // Serve file download.
        drupal_add_http_header('Pragma', 'public');
        drupal_add_http_header('Expires', '0');
        drupal_add_http_header('Cache-Control', 'must-revalidate, post-check=0, pre-check=0');
        drupal_add_http_header('Content-Type', 'application/rdf+xml');
        #drupal_add_http_header('Content-Disposition', 'attachment; filename=' . basename($temp_path . $filename) . ';');
        drupal_add_http_header('Content-Transfer-Encoding', 'binary');
       # drupal_add_http_header('Content-Length', filesize($temp_path . $filename));



       readfile($filepath);

      } else  {
            # return drupal_access_denied();
             header( '204 No Content' );
             exit( 'No Content' );
      }


}
 
